GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/4

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dharma",
    "number": "040-27650909"
}